version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/flexiry
    steps:
      - checkout
      - run:
          name: Update `npm`
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependency
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/flexiry
    steps:
      - checkout
      - run:
          name: Update `npm`
          command: sudo npm install -g npm@latest
      - run:
          name: Install `firebase-tools`
          command: sudo npm i -g firebase-tools
      - attach_workspace:
          at: .
      - run:
          name: Deploy `master` branch to Firebase
          command: firebase deploy --token=$FIREBASE_TOKEN --only hosting

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
